theme: jekyll-theme-cayman
title: Yorgos Askalidis
description: Empowering businesses with data-driven insights for strategic growth. \n Experienced Data Science Specialist and Consultant. Spotify, formely at Instagram